### ISSUE TITLE
Use clojure.spec.alpha for compatibility with clojure 1.9.0 

### ISSUE THREAD

**Issue by chrisfjones** [AvisoNovate/config#10]
I'm on clojure 1.9.0 and would love to use this library but can't due to the references to `clojure.spec`

**Comment by jvtrigueros** [comment]
In the meantime, anyone stumbling into this issue, you can use a jitpack build of the commit that migrates to Clojure 1.9.

https://jitpack.io/#AvisoNovate/config/7dc2bb943d
